### ISSUE TITLE
multipass launch doesn't complete successfully ... known problem?

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/automation-solutions#209]
# Problem

Multipass launch doesn't complete successfully.

Error message: 

```sh
launch failed: The following errors occurred:                                   
timed out waiting for initialization to complete
```

# Reproduce the problem

Following the documentation for [multipass](https://github.com/cloud-native-toolkit/automation-solutions/blob/main/common-files/RUNTIMES.md#multipass). 

* Executed command:

```sh
multipass launch --name cli-tools --cloud-init ./cli-tools.yaml
```

* Error output

```sh
launch failed: The following errors occurred:                                   
timed out waiting for initialization to complete
```

# Environment:

* Multipass: multipass   1.10.1+mac & multipassd  1.10.1+mac
* Mac OS: 12.5.1
* Processor: Intel
* hyperkit: 0.20200908 Homepage: https://github.com/docker/hyperkit License: BSD

# Multipass installation:

I installed multipass with brew:

```sh
brew install --cask multipass
```

**Comment by thomassuedbroecker** [comment]
@triceam @timroster @nheidloff 

I tried to mount directory even when the start was not fully successfully.
I followed the steps to enable the filesystem access, but I got that error:

* Command 

```sh
multipass mount $PWD cli-tools:/automation
```

* Output:

```sh
mount failed: Error enabling mount support in 'cli-tools'                       

Please install the 'multipass-sshfs' snap manually inside the instance.
```

**Comment by thomassuedbroecker** [comment]
# Solution
Ensure no VPN connection is established, when using `multipass`.

**Comment by balasgit** [comment]
FYI - I am running AnyConnect as i can still launch the Multipass with no errors..
