### ISSUE TITLE
README for Turbonomic BOM does not provide instructions to deploy Turbonomic

### ISSUE THREAD

**Issue by vbrsid** [cloud-native-toolkit/automation-solutions#58]
The Turbonomic BOMs under 'automation-solutions' seem to be updated with a structure to deploy Turbonomic on multiple Clouds, including IBM, AWS and Azure. Noticed a few challenges while using these files:

1. The steps to deploy Turbonomic are not indicated in the README (reflects the earlier steps). 
2. Some of the links are broken.
3. We tried to use 'generate.sh' and 'apply' the terraform plan in sequence of the numbers. The argoCD module is going through, but not the others. 
4. Not clear if these files are ready to make the deployment in multiple Clouds or only on an existing OpenShift Cluster in IBM Cloud. 

Once the instructions to deploy Turbonomic are updated, we would like to try deploying on different Clouds.

**Comment by mjperrins** [comment]
we are working this content it will be fixed soon
